apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenhieu8790/meme.git
    targetRevision: main
    path: bootstrap
    directory:
      include: '*.yaml'
      exclude: 'no-use/*'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true