apiVersion: v2
name: cert-manager
description: A Helm chart for deploying cert-manager and related components
type: application
version: "v1.18.2"
appVersion: "1.18.2"

dependencies:
  - name: cert-manager
    version: "v1.18.2"
    alias: application
    repository: "oci://quay.io/jetstack/charts/cert-manager"