version: '3.8'

services:
  jenkins:
    container_name: jenkins_master
    image: jenkins/jenkins:lts
    network_mode: "host"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home: