apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: log-service-update
spec:
  background: false
  rules:
    - name: log-service-update-event
      match:
        any:
          - resources:
              kinds:
                - Service
      # preconditions:
      #   all:
      #     - key: "{{ request.operation }}"
      #       operator: Equals
      #       value: UPDATE
      generate:
        apiVersion: v1
        kind: Event
        name: "service-update-{{ request.object.metadata.name | lower }}-{{ request.uid | lower }}"
        namespace: "{{ request.object.metadata.namespace }}"
        synchronize: false
        data:
          reason: "ServiceUpdated"
          message: "Service 002 '{{ request }}'"
          type: "Normal"
          involvedObject:
            apiVersion: v1
            kind: Service
            name: "{{ request.object.metadata.name }}"
            namespace: "{{ request.object.metadata.namespace }}"
    - name: deny-service-update-event
      match:
        any:
          - resources:
              kinds:
                - Service         
      validate:
        failureAction: Enforce      
        message: "Only argocd can create resources"
        # The `pattern` object defines what pattern will be checked in the resource. In this case, it is looking for `metadata.labels` with `purpose=production`.
        deny:
        conditions:
          all:
          # Deny the request if the serviceAccountName is NOT 'xxx'
          # JMESPath is used for complex conditions
          - key: '{{ request.userInfo.username || `default` }}' # Use 'default' if the field is missing
            operator: NotEquals
            value: "system:serviceaccount:argocd:argocd-application-controller"