apiVersion: v1
kind: Service
metadata:
  name: my-nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service within the cluster
      targetPort: 80 # Port on the pod where the application is listening
      nodePort: 30080 # Port exposed on each node (must be in the range 30000-32767)