apiVersion: v2
name: kyverno
description: A Helm chart for deploying cert-manager and related components
type: application
version: "3.5.1"
appVersion: "v1.15.1"

dependencies:
  - name: kyverno
    version: "3.5.1"
    alias: application
    repository: "https://kyverno.github.io/kyverno/"