apiVersion: v2
name: monitor-grafana
description: A Helm chart for deploying cert-manager and related components
type: application
version: 1.0.0
appVersion: "2.0.0"
dependencies:
  - name: grafana
    version: "10.0.0"
    repository: "https://grafana.github.io/helm-charts"