apiVersion: v1
kind: Pod
metadata:
  name: echo-server2
  labels:
    app: echo-server
    version: v2
spec:
  containers:
  - name: echo-server
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080