apiVersion: v1
kind: Service
metadata:
  name: echo-server2
  namespace: dev    
spec:
  selector:
    app: echo-server
    version: v2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: dev  
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
# ---
# apiVersion: networking.istio.io/v1
# kind: VirtualService
# metadata:
#   name: echo-server
#   namespace: debug
# spec:
#   hosts:
#   - echo-server.dev.svc.cluster.local
#   http:
#   - match:
#     - uri:
#         prefix: /test
#     - uri:
#         prefix: /meme
#     route:
#     - destination:
#         host: echo-server
#         subset: v2
# ---
# apiVersion: networking.istio.io/v1
# kind: DestinationRule
# metadata:
#   name: echo-server
#   namespace: debug
# spec:
#   host: echo-server.dev.svc.cluster.local
#   subsets:
#   - name: v1
#     labels:
#       version: v1
#   - name: v2
#     labels:
#       version: v2 